# Generated by Django 5.2.1 on 2025-05-29 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('contact_data', models.JSONField(verbose_name='Контактные данные')),
                ('price_living', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость проживания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название отеля')),
                ('location', models.JSONField(verbose_name='Местоположение')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звезд')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('creator', models.TextField(verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('Медицинские', 'Медицинские'), ('Поведенческие', 'Поведенческие'), ('Диетические', 'Диетические'), ('Бытовые', 'Бытовые')], max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Специальное требование',
                'verbose_name_plural': 'Специальные требования',
                'ordering': ['category', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Собака', 'Собака'), ('Кошка', 'Кошка'), ('Птица', 'Птица'), ('Грызун', 'Грызун'), ('Другое', 'Другое')], max_length=20, verbose_name='Тип питомца')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['owner', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Require',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(verbose_name='Название продукта')),
                ('required_count', models.IntegerField(verbose_name='Требуемое количество')),
                ('request_date', models.DateField(verbose_name='Дата запроса')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client', verbose_name='Клиент')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hotel', verbose_name='Отель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='RequireBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='Название продукта')),
                ('count_required', models.IntegerField(verbose_name='Требуемое количество')),
                ('request_date', models.DateField(verbose_name='Дата запроса')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client', verbose_name='Клиент')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hotel', verbose_name='Отель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заявка на продукт',
                'verbose_name_plural': 'Заявки на продукты',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер комнаты')),
                ('type', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Комфорт', 'Комфорт'), ('Люкс', 'Люкс')], max_length=20, verbose_name='Тип комнаты')),
                ('availability', models.CharField(choices=[('доступен', 'Доступен'), ('недоступен', 'Недоступен')], default='доступен', max_length=20, verbose_name='Доступность')),
                ('price_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за день')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('pet_friendly', models.CharField(choices=[('Разрешено', 'Разрешено'), ('Запрещено', 'Запрещено')], max_length=20, verbose_name='Разрешены ли питомцы')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Плата за уборку')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['hotel', 'number'],
                'unique_together': {('number', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Дата заезда')),
                ('departure_date', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('действительно', 'Действительно'), ('отменено', 'Отменено'), ('просрочено', 'Просрочено'), ('закрыто', 'Закрыто')], default='действительно', max_length=20, verbose_name='Статус')),
                ('human_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество гостей')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client', verbose_name='Клиент')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.pet', verbose_name='Питомец')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='PetRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий'), ('Критичный', 'Критичный')], max_length=20, verbose_name='Серьезность')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.pet', verbose_name='Питомец')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.specialrequirement', verbose_name='Требование')),
            ],
            options={
                'verbose_name': 'Требование для питомца',
                'verbose_name_plural': 'Требования для питомцев',
                'ordering': ['pet', '-severity'],
                'unique_together': {('pet', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(verbose_name='Местоположение склада')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['hotel'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.warehouse', verbose_name='Склад'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
