# Generated by Django 5.2.1 on 2025-05-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_room_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequireBy',
        ),
    ]
