# Generated by Django 5.2.1 on 2025-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_requireby'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
