# Generated by Django 5.2.1 on 2025-05-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
