# Generated by Django 5.2.1 on 2025-05-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequireBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='Название продукта')),
                ('count_required', models.IntegerField(verbose_name='Требуемое количество')),
                ('request_date', models.DateField(verbose_name='Дата запроса')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client', verbose_name='Клиент')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.hotel', verbose_name='Отель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заявка на продукт',
                'verbose_name_plural': 'Заявки на продукты',
                'ordering': ['-request_date'],
            },
        ),
    ]
