# Generated by Django 5.2.1 on 2025-05-28 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='esexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Exam Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('exam_date', models.DateTimeField(verbose_name='Exam Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Exam Image')),
                ('is_public', models.BooleanField(default=False, verbose_name='Published')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Assigned Users')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-created'],
            },
        ),
    ]
